from turtle import *

def tree(x, y):
    penup()
    goto(x,y)
    pendown()
    color("brown")
    pensize(20)
    left(90)
    forward(50)
    color("green")
    right(90)
    begin_fill()
    circle(25)
    end_fill()

def house(x,y):
    penup()
    goto(x,y)
    pendown()
    pensize(20)
    color("orange red")
    fillcolor("light sky blue")
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()

    penup()
    goto(x-15,y+60) 
    pendown()
    pensize(5)
    color("black")
    fillcolor("red")
    begin_fill()
    forward(80)
    left(130)
    forward(62)
    left(100)
    forward(62)
    end_fill()

def car(x,y):
    penup()
    goto(x,y) 
    pendown()
    pensize(2)
    color("black")
    fillcolor("silver")
    begin_fill()
    left(130)
    forward(100)
    left(90)
    forward(30)
    left(70)
    forward(45)
    left(20)
    forward(40)
    left(30)
    forward(40)
    left(90)
    forward(30)
    end_fill()

    fillcolor("firebrick")

    penup()
    goto(x+10,y-10)
    pendown()
    begin_fill()
    circle(10)
    end_fill()
    penup()
    goto(x+70,y-10)
    pendown()
    begin_fill()
    circle(10)
    end_fill()




tree(0,10)
house(-150,0)
car(100, -20)

hideturtle()
exitonclick()
